sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t mowen98/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mowen98/docker-react npm run test